### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by demurgos** [ivanpopelyshev/shumway#3]
Hi,
What is the status of this project? What are the main changes compared to `mozilla/shumway`? What changes do you plan? What is the goal of this fork?

I am also interested in having a working Flash Player. I have considered forking and refactoring Shumway but eventually started a fresh project ([Open Flash](https://github.com/open-flash/open-flash) - but not ready yet) for architectural reasons. I also actively follow the ["open source Flash" petition](https://github.com/open-source-flash/open-source-flash/) and related projects.
It seems that you managed to do a good chunk of work here so I'd be interested to learn more about this and hear about what you think.

**Comment by ivanpopelyshev** [comment]
The goal is to convert it to PixiJS plugin and make AVM optional. Two types of users:
1. Those who want move from Flash and ready to convert their code to typescript
2. Those who want use Animate CC to make UI and animations

There's https://github.com/ivanpopelyshev/shumway/tree/refactor-flash-base branch that is a two month behind of what i have now, I'll update it in a few days and add an example.

https://github.com/ivanpopelyshev/shumway/tree/refactor-flash-base/src/flash-legacy/statics - All classes are just general JS classes and not abominations with two prototypes. They have "_sec" injected in them, of course. All statics are stored in special objects, like companion objects in Scala or Kotlin. I create all of those objects in SecurityDomain.

I also dropped AVM support, however I'll add optional AVM2 module later, just to allow people to look how their old code works on new runtime. AVM1 should die, because its easier to just convert old FLA files with JSFL scripts than to support it.

I can launch SWF's without AVM, and my hello world example is small compared to shuobject.

**Comment by ivanpopelyshev** [comment]
I have been working on this for seven months now

**Comment by demurgos** [comment]
Okay,
Thanks for the reply. I'll look into PixiJS and into your changes when I'll have more time.
It's nice to hear that you cleaned-up the AVM implementation: I agree that it was pretty messy.

I am happy that you managed to make the AVM optional. Just to be sure, it means that it is not shipped to the client at all? Would it be possible to pull it out of Shumway entirely and have it in a different repo? You removed the renderer dependency on the AVM but what about the other direction: is there an AVM dependency on the renderer?
I just started to work on the AVM myself so this kind of question really interests me. I currently want to have something similar to V8 and its bindings to either Node or the DOM. (Standalone AVM with optional bindings to the Flash renderer)

**Comment by ivanpopelyshev** [comment]
Yes, AVM not shipped at client, at all. Yep, we'll make separate repo when example is ready. 

Yeah, good thing i dont need AVM at all - I have access to commercial converter that translates huge number of lines of AS3 code to TS :) We even added `int` and `uint` types in typescript!

Project has two parts:
1. open-source runtime for us, indies. Based on pixi
2. commercial converter for companies who want to migrate their big codebases and resources to efficient gl format, that's far faster than that GAP thing.

Last week i found two bugs in chromium, and the week before that bug in mozilla, and i dont count how much flash bugs we've found, both old and "new" (no one wrote about them in internets)

**Comment by ivanpopelyshev** [comment]
And now we have real problem: background appears through seams in graphics shapes. And shumway renderer cant deal with it. Do you have any ideas?

**Comment by demurgos** [comment]
Okay, great for the VM.

Regarding the background and seams, are you referring to the issue demonstrated [in this example](https://jsfiddle.net/9zs0pdc9/3/)?

```html
<canvas id="cvs" style="background: red;" width="100" height="100"></canvas>
```

```javascript
const cvs = document.getElementById("cvs");
const ctx = cvs.getContext("2d");

ctx.fillStyle = "white";

ctx.beginPath();
ctx.moveTo(20, 20);
ctx.lineTo(80, 20);
ctx.lineTo(80, 80);
ctx.fill();

ctx.beginPath();
ctx.moveTo(20, 20);
ctx.lineTo(20, 80);
ctx.lineTo(80, 80);
ctx.fill();
```

I draw two triangles forming a square but you can still see the diagonal:

![image](https://user-images.githubusercontent.com/2262218/37996583-77f0d376-3218-11e8-8fae-9c40044a5ae3.png)

This is an old issue that I found when decoding SWF shapes (already there about 8 years ago). I can think of two solutions.
- Render an upscaled aliased version and then resize it. Easy but may be inefficient.
- Try to do some bleeding by enlarging the shape. More complex to do right.

I believe that Adobe uses some form of the first solution by tracking the colored subpixels (it'd make sense that they use twips).

I tried to quickly apply the first solution on my canvas example but haven't really managed to do it. I need to take a closer look at it because I also encounter this problem quite often.

After some (very) quick search, I don't think it's possible to disable anti-aliasing on shape primitives when using the 2d context. A reliable solution would be to use webgl but this a lot more involved.

**Comment by ivanpopelyshev** [comment]
the only good solution i see is to render shapes in separate canvas and use additive blending there.

I remember that I "healed" exported svg file by adding a filter that removed alpha from some places.

**Comment by ivanpopelyshev** [comment]
It is done, SFW imports dont have that problem anymore. Manual graphics still broken, but its not important.

**Comment by ivanpopelyshev** [comment]
I sent pixijs slack invitation to you, we are forming a channel :)
